use std::time::{Duration, Instant};

use hmac::{Hmac, Mac};
use sha2::Sha256;
use spake2::{Ed25519Group, Identity, Password, Spake2};

use crate::crypto::exchange::hkdf_sha256;
use crate::identity::{LocalIdentity, PeerId};

use super::messages::*;

/// HKDF info string for pairing session key derivation.
const HKDF_INFO_PAIRING_SESSION: &[u8] = b"cairn-pairing-session-key-v1";

/// HMAC key derivation info for key confirmation.
const HKDF_INFO_KEY_CONFIRM: &[u8] = b"cairn-pairing-key-confirm-v1";

/// Fixed SPAKE2 identity labels.
const SPAKE2_ID_INITIATOR: &[u8] = b"cairn-initiator";
const SPAKE2_ID_RESPONDER: &[u8] = b"cairn-responder";

/// Default pairing timeout.
pub const DEFAULT_PAIRING_TIMEOUT: Duration = Duration::from_secs(300);

/// Pairing-specific error type.
#[derive(Debug, thiserror::Error, Clone)]
pub enum PairingError {
    #[error("pairing timed out after {0:?}")]
    Timeout(Duration),

    #[error("PAKE authentication failed")]
    PakeFailure,

    #[error("rejected by peer: {0}")]
    Rejected(PairRejectReason),

    #[error("invalid state transition: expected {expected}, got {actual}")]
    InvalidTransition { expected: String, actual: String },

    #[error("invalid message for current state")]
    InvalidMessage,

    #[error("SPAKE2 protocol error: {0}")]
    Spake2Error(String),
}

/// Pairing session state.
#[derive(Debug)]
pub enum PairingState {
    /// Idle — not started.
    Idle,
    /// Sent PairRequest, waiting for PairChallenge (initiator, initiation flow).
    AwaitingPakeExchange,
    /// PAKE complete or standard flow — waiting for SAS verification / key confirmation.
    AwaitingVerification,
    /// Sent PairConfirm, waiting for peer's PairConfirm.
    AwaitingConfirmation,
    /// Pairing completed successfully.
    Completed,
    /// Pairing failed.
    Failed(PairingError),
}

impl std::fmt::Display for PairingState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PairingState::Idle => write!(f, "Idle"),
            PairingState::AwaitingPakeExchange => write!(f, "AwaitingPakeExchange"),
            PairingState::AwaitingVerification => write!(f, "AwaitingVerification"),
            PairingState::AwaitingConfirmation => write!(f, "AwaitingConfirmation"),
            PairingState::Completed => write!(f, "Completed"),
            PairingState::Failed(e) => write!(f, "Failed({e})"),
        }
    }
}

/// Whether this session is acting as initiator or responder.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PairingRole {
    Initiator,
    Responder,
}

/// A pairing session driving the SPAKE2 exchange and state transitions.
pub struct PairingSession {
    state: PairingState,
    role: PairingRole,
    flow_type: PairingFlowType,
    local_identity: LocalIdentity,
    remote_peer_id: Option<PeerId>,
    /// SPAKE2 state (consumed on `finish`).
    spake2_state: Option<Spake2<Ed25519Group>>,
    /// SPAKE2 outbound message (stored by responder for PairChallenge).
    spake2_outbound: Option<Vec<u8>>,
    /// Derived shared key from SPAKE2 exchange.
    shared_key: Option<Vec<u8>>,
    /// Nonce generated by the initiator.
    local_nonce: Vec<u8>,
    /// Nonce from the remote peer.
    remote_nonce: Option<Vec<u8>>,
    created_at: Instant,
    timeout: Duration,
}

impl std::fmt::Debug for PairingSession {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("PairingSession")
            .field("state", &self.state)
            .field("role", &self.role)
            .field("flow_type", &self.flow_type)
            .field("remote_peer_id", &self.remote_peer_id)
            .field("timeout", &self.timeout)
            .finish_non_exhaustive()
    }
}

impl PairingSession {
    /// Create a new initiator session for the initiation flow (SPAKE2).
    ///
    /// Returns the session and the outbound `PairRequest` message to send.
    pub fn new_initiator(
        identity: LocalIdentity,
        password: &[u8],
        timeout: Duration,
    ) -> (Self, PairingMessage) {
        let nonce = generate_nonce();

        let (spake2_state, outbound_msg) = Spake2::<Ed25519Group>::start_a(
            &Password::new(password),
            &Identity::new(SPAKE2_ID_INITIATOR),
            &Identity::new(SPAKE2_ID_RESPONDER),
        );

        let request = PairRequest {
            peer_id: identity.peer_id().clone(),
            nonce: nonce.clone(),
            pake_msg: Some(outbound_msg),
            flow_type: PairingFlowType::Initiation,
        };

        let session = Self {
            state: PairingState::AwaitingPakeExchange,
            role: PairingRole::Initiator,
            flow_type: PairingFlowType::Initiation,
            local_identity: identity,
            remote_peer_id: None,
            spake2_state: Some(spake2_state),
            spake2_outbound: None,
            shared_key: None,
            local_nonce: nonce,
            remote_nonce: None,
            created_at: Instant::now(),
            timeout,
        };

        (session, PairingMessage::Request(request))
    }

    /// Create a new initiator session for the standard flow (no SPAKE2).
    ///
    /// Returns the session and the outbound `PairRequest` message.
    pub fn new_standard_initiator(
        identity: LocalIdentity,
        timeout: Duration,
    ) -> (Self, PairingMessage) {
        let nonce = generate_nonce();

        let request = PairRequest {
            peer_id: identity.peer_id().clone(),
            nonce: nonce.clone(),
            pake_msg: None,
            flow_type: PairingFlowType::Standard,
        };

        let session = Self {
            state: PairingState::AwaitingVerification,
            role: PairingRole::Initiator,
            flow_type: PairingFlowType::Standard,
            local_identity: identity,
            remote_peer_id: None,
            spake2_state: None,
            spake2_outbound: None,
            shared_key: None,
            local_nonce: nonce,
            remote_nonce: None,
            created_at: Instant::now(),
            timeout,
        };

        (session, PairingMessage::Request(request))
    }

    /// Create a new responder session for the initiation flow (SPAKE2).
    ///
    /// Call `handle_message` with the received `PairRequest` to proceed.
    pub fn new_responder(identity: LocalIdentity, password: &[u8], timeout: Duration) -> Self {
        let nonce = generate_nonce();
        let (spake2_state, outbound) = Spake2::<Ed25519Group>::start_b(
            &Password::new(password),
            &Identity::new(SPAKE2_ID_INITIATOR),
            &Identity::new(SPAKE2_ID_RESPONDER),
        );

        Self {
            state: PairingState::Idle,
            role: PairingRole::Responder,
            flow_type: PairingFlowType::Initiation,
            local_identity: identity,
            remote_peer_id: None,
            spake2_state: Some(spake2_state),
            spake2_outbound: Some(outbound),
            shared_key: None,
            local_nonce: nonce,
            remote_nonce: None,
            created_at: Instant::now(),
            timeout,
        }
    }

    /// Create a new responder session for the standard flow (no SPAKE2).
    pub fn new_standard_responder(identity: LocalIdentity, timeout: Duration) -> Self {
        let nonce = generate_nonce();
        Self {
            state: PairingState::Idle,
            role: PairingRole::Responder,
            flow_type: PairingFlowType::Standard,
            local_identity: identity,
            remote_peer_id: None,
            spake2_state: None,
            spake2_outbound: None,
            shared_key: None,
            local_nonce: nonce,
            remote_nonce: None,
            created_at: Instant::now(),
            timeout,
        }
    }

    /// Set a pre-established shared key (from Noise XX handshake, standard flow).
    pub fn set_shared_key(&mut self, key: Vec<u8>) {
        self.shared_key = Some(key);
    }

    /// After SAS verification (or SPAKE2 completion), produce a key confirmation
    /// message and advance to `AwaitingConfirmation`.
    ///
    /// Call this when the local side is ready to confirm the pairing (e.g., after
    /// the user confirms the SAS matches). Returns a `PairResponse` (initiator)
    /// or `PairConfirm` (responder) to send to the peer.
    pub fn send_key_confirmation(&mut self) -> Result<PairingMessage, PairingError> {
        if !matches!(self.state, PairingState::AwaitingVerification) {
            return Err(PairingError::InvalidTransition {
                expected: "AwaitingVerification".into(),
                actual: self.state.to_string(),
            });
        }

        let label = match self.role {
            PairingRole::Initiator => b"initiator" as &[u8],
            PairingRole::Responder => b"responder" as &[u8],
        };
        let confirmation = self.compute_key_confirmation(label)?;
        self.state = PairingState::AwaitingConfirmation;

        match self.role {
            PairingRole::Initiator => Ok(PairingMessage::Response(PairResponse {
                key_confirmation: confirmation,
            })),
            PairingRole::Responder => Ok(PairingMessage::Confirm(PairConfirm {
                key_confirmation: confirmation,
            })),
        }
    }

    /// Process an incoming pairing message. Returns an optional outbound response.
    pub fn handle_message(
        &mut self,
        msg: PairingMessage,
    ) -> Result<Option<PairingMessage>, PairingError> {
        if self.is_expired() {
            let err = PairingError::Timeout(self.timeout);
            self.state = PairingState::Failed(err.clone());
            return Err(err);
        }

        match msg {
            PairingMessage::Request(req) => self.handle_request(req),
            PairingMessage::Challenge(chal) => self.handle_challenge(chal),
            PairingMessage::Response(resp) => self.handle_response(resp),
            PairingMessage::Confirm(confirm) => self.handle_confirm(confirm),
            PairingMessage::Reject(reject) => self.handle_reject(reject),
            PairingMessage::Revoke(_) => {
                // Revoke is handled at a higher level (session/trust store cleanup).
                Ok(None)
            }
        }
    }

    /// Check if this session has expired.
    pub fn is_expired(&self) -> bool {
        self.created_at.elapsed() > self.timeout
    }

    /// Get the shared key (only available in Completed state).
    pub fn shared_key(&self) -> Option<&[u8]> {
        if matches!(self.state, PairingState::Completed) {
            self.shared_key.as_deref()
        } else {
            None
        }
    }

    /// Get the current state.
    pub fn state(&self) -> &PairingState {
        &self.state
    }

    /// Get the remote peer ID (if known).
    pub fn remote_peer_id(&self) -> Option<&PeerId> {
        self.remote_peer_id.as_ref()
    }

    /// Get the flow type.
    pub fn flow_type(&self) -> PairingFlowType {
        self.flow_type
    }

    /// Get the role.
    pub fn role(&self) -> PairingRole {
        self.role
    }

    // --- Message handlers ---

    fn handle_request(&mut self, req: PairRequest) -> Result<Option<PairingMessage>, PairingError> {
        // Responder receives PairRequest
        if self.role != PairingRole::Responder {
            return Err(PairingError::InvalidTransition {
                expected: "Responder role".into(),
                actual: "Initiator role".into(),
            });
        }

        if !matches!(self.state, PairingState::Idle) {
            return Err(PairingError::InvalidTransition {
                expected: "Idle".into(),
                actual: self.state.to_string(),
            });
        }

        self.remote_peer_id = Some(req.peer_id);
        self.remote_nonce = Some(req.nonce);

        match req.flow_type {
            PairingFlowType::Initiation => {
                let pake_msg = req.pake_msg.ok_or(PairingError::InvalidMessage)?;

                // Finish SPAKE2 with the initiator's message.
                let spake2_state = self.spake2_state.take().ok_or_else(|| {
                    PairingError::Spake2Error("SPAKE2 state not initialized".into())
                })?;

                let raw_key = spake2_state
                    .finish(&pake_msg)
                    .map_err(|_| PairingError::PakeFailure)?;

                // Derive session key via HKDF
                let session_key = self.derive_session_key(&raw_key)?;
                self.shared_key = Some(session_key);

                // Retrieve the stored SPAKE2 outbound message for the challenge.
                let outbound = self.spake2_outbound.take().ok_or_else(|| {
                    PairingError::Spake2Error("SPAKE2 outbound message not stored".into())
                })?;

                self.state = PairingState::AwaitingVerification;

                Ok(Some(PairingMessage::Challenge(PairChallenge {
                    peer_id: self.local_identity.peer_id().clone(),
                    nonce: self.local_nonce.clone(),
                    pake_msg: outbound,
                })))
            }
            PairingFlowType::Standard => {
                // Standard flow — no PAKE exchange needed.
                // Transition to AwaitingVerification (SAS verification).
                self.state = PairingState::AwaitingVerification;
                Ok(None)
            }
        }
    }

    fn handle_challenge(
        &mut self,
        chal: PairChallenge,
    ) -> Result<Option<PairingMessage>, PairingError> {
        // Initiator receives PairChallenge
        if self.role != PairingRole::Initiator {
            return Err(PairingError::InvalidTransition {
                expected: "Initiator role".into(),
                actual: "Responder role".into(),
            });
        }

        if !matches!(self.state, PairingState::AwaitingPakeExchange) {
            return Err(PairingError::InvalidTransition {
                expected: "AwaitingPakeExchange".into(),
                actual: self.state.to_string(),
            });
        }

        self.remote_peer_id = Some(chal.peer_id);
        self.remote_nonce = Some(chal.nonce);

        // Finish SPAKE2 with responder's message
        let spake2_state = self
            .spake2_state
            .take()
            .ok_or_else(|| PairingError::Spake2Error("SPAKE2 state already consumed".into()))?;

        let raw_key = spake2_state
            .finish(&chal.pake_msg)
            .map_err(|_| PairingError::PakeFailure)?;

        // Derive session key
        let session_key = self.derive_session_key(&raw_key)?;
        self.shared_key = Some(session_key);

        // Compute key confirmation HMAC
        let confirmation = self.compute_key_confirmation(b"initiator")?;

        self.state = PairingState::AwaitingConfirmation;
        Ok(Some(PairingMessage::Response(PairResponse {
            key_confirmation: confirmation,
        })))
    }

    fn handle_response(
        &mut self,
        resp: PairResponse,
    ) -> Result<Option<PairingMessage>, PairingError> {
        // Responder receives PairResponse (key confirmation from initiator)
        if self.role != PairingRole::Responder {
            return Err(PairingError::InvalidTransition {
                expected: "Responder role".into(),
                actual: "Initiator role".into(),
            });
        }

        if !matches!(self.state, PairingState::AwaitingVerification) {
            return Err(PairingError::InvalidTransition {
                expected: "AwaitingVerification".into(),
                actual: self.state.to_string(),
            });
        }

        // Verify initiator's key confirmation
        let expected = self.compute_key_confirmation(b"initiator")?;
        if !constant_time_eq(&resp.key_confirmation, &expected) {
            self.state = PairingState::Failed(PairingError::PakeFailure);
            return Err(PairingError::PakeFailure);
        }

        // Send our own key confirmation
        let confirmation = self.compute_key_confirmation(b"responder")?;

        self.state = PairingState::AwaitingConfirmation;
        Ok(Some(PairingMessage::Confirm(PairConfirm {
            key_confirmation: confirmation,
        })))
    }

    fn handle_confirm(
        &mut self,
        confirm: PairConfirm,
    ) -> Result<Option<PairingMessage>, PairingError> {
        if !matches!(self.state, PairingState::AwaitingConfirmation) {
            return Err(PairingError::InvalidTransition {
                expected: "AwaitingConfirmation".into(),
                actual: self.state.to_string(),
            });
        }

        // Verify the peer's key confirmation
        let label = match self.role {
            PairingRole::Initiator => b"responder" as &[u8],
            PairingRole::Responder => b"initiator" as &[u8],
        };

        let expected = self.compute_key_confirmation(label)?;
        if !constant_time_eq(&confirm.key_confirmation, &expected) {
            self.state = PairingState::Failed(PairingError::PakeFailure);
            return Err(PairingError::PakeFailure);
        }

        self.state = PairingState::Completed;

        // Initiator sends their own Confirm back
        if self.role == PairingRole::Initiator {
            let our_confirm = self.compute_key_confirmation(b"initiator")?;
            return Ok(Some(PairingMessage::Confirm(PairConfirm {
                key_confirmation: our_confirm,
            })));
        }

        Ok(None)
    }

    fn handle_reject(
        &mut self,
        reject: PairReject,
    ) -> Result<Option<PairingMessage>, PairingError> {
        let err = PairingError::Rejected(reject.reason);
        self.state = PairingState::Failed(err.clone());
        Err(err)
    }

    // --- Key derivation helpers ---

    fn derive_session_key(&self, raw_key: &[u8]) -> Result<Vec<u8>, PairingError> {
        // salt = initiator_nonce || responder_nonce (or just local_nonce if remote not yet known)
        let mut salt = Vec::new();
        match self.role {
            PairingRole::Initiator => {
                salt.extend_from_slice(&self.local_nonce);
                if let Some(ref remote_nonce) = self.remote_nonce {
                    salt.extend_from_slice(remote_nonce);
                }
            }
            PairingRole::Responder => {
                if let Some(ref remote_nonce) = self.remote_nonce {
                    salt.extend_from_slice(remote_nonce);
                }
                salt.extend_from_slice(&self.local_nonce);
            }
        }

        let mut session_key = vec![0u8; 32];
        hkdf_sha256(
            raw_key,
            Some(&salt),
            HKDF_INFO_PAIRING_SESSION,
            &mut session_key,
        )
        .map_err(|e| PairingError::Spake2Error(format!("HKDF failed: {e}")))?;
        Ok(session_key)
    }

    fn compute_key_confirmation(&self, label: &[u8]) -> Result<Vec<u8>, PairingError> {
        let shared_key = self
            .shared_key
            .as_ref()
            .ok_or(PairingError::InvalidMessage)?;

        // Derive a confirmation key via HKDF
        let mut confirm_key = vec![0u8; 32];
        hkdf_sha256(shared_key, None, HKDF_INFO_KEY_CONFIRM, &mut confirm_key)
            .map_err(|e| PairingError::Spake2Error(format!("HKDF failed: {e}")))?;

        // HMAC-SHA256(confirm_key, label)
        let mut mac = Hmac::<Sha256>::new_from_slice(&confirm_key)
            .map_err(|e| PairingError::Spake2Error(format!("HMAC init failed: {e}")))?;
        mac.update(label);
        Ok(mac.finalize().into_bytes().to_vec())
    }
}

/// Generate a 16-byte random nonce.
fn generate_nonce() -> Vec<u8> {
    use rand::RngCore;
    let mut nonce = vec![0u8; 16];
    rand::thread_rng().fill_bytes(&mut nonce);
    nonce
}

/// Constant-time byte comparison.
fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    use subtle::ConstantTimeEq;
    if a.len() != b.len() {
        return false;
    }
    a.ct_eq(b).into()
}

#[cfg(test)]
mod tests {
    use super::*;

    const TEST_PASSWORD: &[u8] = b"test-pairing-password-42";

    // --- Initiation flow tests ---

    #[test]
    fn initiation_flow_initiator_creates_request() {
        let identity = LocalIdentity::generate();
        let (session, msg) =
            PairingSession::new_initiator(identity, TEST_PASSWORD, DEFAULT_PAIRING_TIMEOUT);

        assert!(matches!(
            session.state(),
            PairingState::AwaitingPakeExchange
        ));
        assert_eq!(session.role(), PairingRole::Initiator);
        assert_eq!(session.flow_type(), PairingFlowType::Initiation);

        match msg {
            PairingMessage::Request(req) => {
                assert_eq!(req.flow_type, PairingFlowType::Initiation);
                assert!(req.pake_msg.is_some());
                assert_eq!(req.nonce.len(), 16);
            }
            _ => panic!("expected PairRequest"),
        }
    }

    #[test]
    fn initiation_flow_full_exchange() {
        let alice_id = LocalIdentity::generate();
        let bob_id = LocalIdentity::generate();

        // Alice creates an initiator session with a password
        let (mut alice, alice_req_msg) =
            PairingSession::new_initiator(alice_id, TEST_PASSWORD, DEFAULT_PAIRING_TIMEOUT);
        assert!(matches!(alice.state(), PairingState::AwaitingPakeExchange));

        // Bob creates a responder session with the same password
        let mut bob = PairingSession::new_responder(bob_id, TEST_PASSWORD, DEFAULT_PAIRING_TIMEOUT);
        assert!(matches!(bob.state(), PairingState::Idle));

        // Bob handles Alice's PairRequest, gets a PairChallenge back
        let bob_reply = bob.handle_message(alice_req_msg).unwrap();
        assert!(bob_reply.is_some());
        assert!(matches!(bob.state(), PairingState::AwaitingVerification));
        let challenge = bob_reply.unwrap();
        assert!(matches!(challenge, PairingMessage::Challenge(_)));

        // Alice handles Bob's PairChallenge, gets a PairResponse (key confirmation)
        let alice_reply = alice.handle_message(challenge).unwrap();
        assert!(alice_reply.is_some());
        assert!(matches!(alice.state(), PairingState::AwaitingConfirmation));

        // Bob handles Alice's PairResponse, verifies key confirmation, sends PairConfirm
        let bob_confirm = bob.handle_message(alice_reply.unwrap()).unwrap();
        assert!(bob_confirm.is_some());
        assert!(matches!(bob.state(), PairingState::AwaitingConfirmation));

        // Alice handles Bob's PairConfirm, completes
        let alice_final = alice.handle_message(bob_confirm.unwrap()).unwrap();
        assert!(matches!(alice.state(), PairingState::Completed));
        assert!(alice.shared_key().is_some());

        // If Alice sent a confirm back, Bob processes it
        if let Some(confirm_back) = alice_final {
            let _ = bob.handle_message(confirm_back).unwrap();
            assert!(matches!(bob.state(), PairingState::Completed));
            assert!(bob.shared_key().is_some());
        }

        // Both sides derived the same shared key
        assert_eq!(alice.shared_key().unwrap(), bob.shared_key().unwrap());
    }

    #[test]
    fn spake2_wrong_password_produces_different_keys() {
        let (alice_state, alice_msg) = Spake2::<Ed25519Group>::start_a(
            &Password::new(b"correct-password"),
            &Identity::new(SPAKE2_ID_INITIATOR),
            &Identity::new(SPAKE2_ID_RESPONDER),
        );

        let (bob_state, bob_msg) = Spake2::<Ed25519Group>::start_b(
            &Password::new(b"wrong-password"),
            &Identity::new(SPAKE2_ID_INITIATOR),
            &Identity::new(SPAKE2_ID_RESPONDER),
        );

        let alice_key = alice_state.finish(&bob_msg).unwrap();
        let bob_key = bob_state.finish(&alice_msg).unwrap();

        // With mismatched passwords, the derived keys won't match.
        assert_ne!(alice_key, bob_key);
    }

    // --- Standard flow tests ---

    #[test]
    fn standard_flow_initiator_creates_request() {
        let identity = LocalIdentity::generate();
        let (session, msg) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);

        assert!(matches!(
            session.state(),
            PairingState::AwaitingVerification
        ));
        assert_eq!(session.role(), PairingRole::Initiator);
        assert_eq!(session.flow_type(), PairingFlowType::Standard);

        match msg {
            PairingMessage::Request(req) => {
                assert_eq!(req.flow_type, PairingFlowType::Standard);
                assert!(req.pake_msg.is_none());
            }
            _ => panic!("expected PairRequest"),
        }
    }

    #[test]
    fn standard_flow_responder_handles_request() {
        let bob_id = LocalIdentity::generate();
        let mut responder = PairingSession::new_standard_responder(bob_id, DEFAULT_PAIRING_TIMEOUT);

        let alice_id = LocalIdentity::generate();
        let request = PairRequest {
            peer_id: alice_id.peer_id().clone(),
            nonce: vec![0; 16],
            pake_msg: None,
            flow_type: PairingFlowType::Standard,
        };

        let result = responder.handle_message(PairingMessage::Request(request));
        assert!(result.is_ok());
        assert!(matches!(
            responder.state(),
            PairingState::AwaitingVerification
        ));
    }

    // --- Key confirmation tests ---

    #[test]
    fn key_confirmation_is_deterministic() {
        let identity = LocalIdentity::generate();
        let (mut session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);
        session.set_shared_key(vec![42u8; 32]);

        let c1 = session.compute_key_confirmation(b"test").unwrap();
        let c2 = session.compute_key_confirmation(b"test").unwrap();
        assert_eq!(c1, c2);
    }

    #[test]
    fn key_confirmation_differs_by_label() {
        let identity = LocalIdentity::generate();
        let (mut session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);
        session.set_shared_key(vec![42u8; 32]);

        let c_init = session.compute_key_confirmation(b"initiator").unwrap();
        let c_resp = session.compute_key_confirmation(b"responder").unwrap();
        assert_ne!(c_init, c_resp);
    }

    #[test]
    fn key_confirmation_differs_by_key() {
        let id1 = LocalIdentity::generate();
        let id2 = LocalIdentity::generate();

        let (mut s1, _) = PairingSession::new_standard_initiator(id1, DEFAULT_PAIRING_TIMEOUT);
        let (mut s2, _) = PairingSession::new_standard_initiator(id2, DEFAULT_PAIRING_TIMEOUT);

        s1.set_shared_key(vec![1u8; 32]);
        s2.set_shared_key(vec![2u8; 32]);

        let c1 = s1.compute_key_confirmation(b"test").unwrap();
        let c2 = s2.compute_key_confirmation(b"test").unwrap();
        assert_ne!(c1, c2);
    }

    // --- Rejection tests ---

    #[test]
    fn reject_transitions_to_failed() {
        let identity = LocalIdentity::generate();
        let (mut session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);

        let result = session.handle_message(PairingMessage::Reject(PairReject {
            reason: PairRejectReason::UserRejected,
        }));

        assert!(result.is_err());
        assert!(matches!(session.state(), PairingState::Failed(_)));
    }

    // --- Timeout tests ---

    #[test]
    fn expired_session_rejects_messages() {
        let identity = LocalIdentity::generate();
        let (mut session, _) = PairingSession::new_standard_initiator(
            identity,
            Duration::from_millis(0), // instantly expired
        );

        // Give it a moment to expire
        std::thread::sleep(Duration::from_millis(1));

        let result = session.handle_message(PairingMessage::Confirm(PairConfirm {
            key_confirmation: vec![],
        }));

        assert!(result.is_err());
        match result.unwrap_err() {
            PairingError::Timeout(_) => {}
            other => panic!("expected Timeout, got: {other}"),
        }
    }

    #[test]
    fn non_expired_session_is_not_expired() {
        let identity = LocalIdentity::generate();
        let (session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);
        assert!(!session.is_expired());
    }

    // --- Invalid state transition tests ---

    #[test]
    fn initiator_rejects_pair_request() {
        let identity = LocalIdentity::generate();
        let (mut session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);

        let other_id = LocalIdentity::generate();
        let result = session.handle_message(PairingMessage::Request(PairRequest {
            peer_id: other_id.peer_id().clone(),
            nonce: vec![0; 16],
            pake_msg: None,
            flow_type: PairingFlowType::Standard,
        }));

        assert!(result.is_err());
        match result.unwrap_err() {
            PairingError::InvalidTransition { .. } => {}
            other => panic!("expected InvalidTransition, got: {other}"),
        }
    }

    #[test]
    fn responder_rejects_challenge() {
        let identity = LocalIdentity::generate();
        let mut session = PairingSession::new_standard_responder(identity, DEFAULT_PAIRING_TIMEOUT);

        let other_id = LocalIdentity::generate();
        let result = session.handle_message(PairingMessage::Challenge(PairChallenge {
            peer_id: other_id.peer_id().clone(),
            nonce: vec![0; 16],
            pake_msg: vec![],
        }));

        assert!(result.is_err());
    }

    // --- Shared key access tests ---

    #[test]
    fn shared_key_not_available_before_completion() {
        let identity = LocalIdentity::generate();
        let (mut session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);
        session.set_shared_key(vec![42u8; 32]);

        // Not in Completed state yet
        assert!(session.shared_key().is_none());
    }

    // --- Full standard flow with key confirmation ---

    #[test]
    fn standard_flow_key_confirmation_exchange() {
        let alice_id = LocalIdentity::generate();
        let bob_id = LocalIdentity::generate();

        let (mut alice, alice_req_msg) =
            PairingSession::new_standard_initiator(alice_id, DEFAULT_PAIRING_TIMEOUT);

        let mut bob = PairingSession::new_standard_responder(bob_id, DEFAULT_PAIRING_TIMEOUT);

        // Bob handles Alice's request
        let _bob_reply = bob.handle_message(alice_req_msg).unwrap();

        // Both have the same shared key (simulated — in real flow, Noise XX provides this)
        let shared = vec![0xAB; 32];
        alice.set_shared_key(shared.clone());
        bob.set_shared_key(shared);

        // Set nonces so both sides use the same salt for key confirmation.
        bob.remote_nonce = Some(alice.local_nonce.clone());
        alice.remote_nonce = Some(bob.local_nonce.clone());

        // Alice sends key confirmation (PairResponse) and advances to AwaitingConfirmation.
        let alice_response = alice.send_key_confirmation().unwrap();
        assert!(matches!(alice.state(), PairingState::AwaitingConfirmation));

        // Bob receives Alice's PairResponse, verifies, sends PairConfirm.
        let bob_reply = bob.handle_message(alice_response).unwrap();
        assert!(bob_reply.is_some());
        assert!(matches!(bob.state(), PairingState::AwaitingConfirmation));

        // Alice receives Bob's PairConfirm, verifies, completes.
        let alice_reply = alice.handle_message(bob_reply.unwrap()).unwrap();
        assert!(matches!(alice.state(), PairingState::Completed));
        assert!(alice.shared_key().is_some());

        // If Alice sent a confirm back, Bob processes it to complete.
        if let Some(alice_confirm_back) = alice_reply {
            let _ = bob.handle_message(alice_confirm_back).unwrap();
            assert!(matches!(bob.state(), PairingState::Completed));
            assert!(bob.shared_key().is_some());
        }
    }

    #[test]
    fn wrong_key_confirmation_fails() {
        let alice_id = LocalIdentity::generate();
        let bob_id = LocalIdentity::generate();

        let (mut alice, alice_req_msg) =
            PairingSession::new_standard_initiator(alice_id, DEFAULT_PAIRING_TIMEOUT);

        let mut bob = PairingSession::new_standard_responder(bob_id, DEFAULT_PAIRING_TIMEOUT);

        bob.handle_message(alice_req_msg).unwrap();

        // Set different shared keys to simulate MITM
        alice.set_shared_key(vec![0xAA; 32]);
        bob.set_shared_key(vec![0xBB; 32]);

        bob.remote_nonce = Some(alice.local_nonce.clone());
        alice.remote_nonce = Some(bob.local_nonce.clone());

        // Alice sends her key confirmation (derived from her key)
        let alice_confirm = alice.compute_key_confirmation(b"initiator").unwrap();

        // Bob tries to verify — should fail because keys differ
        let result = bob.handle_message(PairingMessage::Response(PairResponse {
            key_confirmation: alice_confirm,
        }));

        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), PairingError::PakeFailure));
        assert!(matches!(bob.state(), PairingState::Failed(_)));
    }

    // --- Constant-time comparison tests ---

    #[test]
    fn constant_time_eq_works() {
        assert!(constant_time_eq(b"hello", b"hello"));
        assert!(!constant_time_eq(b"hello", b"world"));
        assert!(!constant_time_eq(b"hello", b"hell"));
        assert!(constant_time_eq(b"", b""));
    }

    // --- Session key derivation test ---

    #[test]
    fn session_key_derivation_is_deterministic() {
        let identity = LocalIdentity::generate();
        let (session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);

        let raw_key = vec![0xFF; 32];
        let k1 = session.derive_session_key(&raw_key).unwrap();
        let k2 = session.derive_session_key(&raw_key).unwrap();
        assert_eq!(k1, k2);
        assert_eq!(k1.len(), 32);
    }

    // --- Nonce uniqueness test ---

    #[test]
    fn nonces_are_unique() {
        let n1 = generate_nonce();
        let n2 = generate_nonce();
        assert_ne!(n1, n2);
        assert_eq!(n1.len(), 16);
    }

    // --- Error display tests ---

    #[test]
    fn pairing_error_display() {
        assert!(PairingError::PakeFailure.to_string().contains("PAKE"));
        assert!(PairingError::InvalidMessage
            .to_string()
            .contains("invalid message"));
        assert!(PairingError::Timeout(Duration::from_secs(300))
            .to_string()
            .contains("300"));
        assert!(PairingError::Rejected(PairRejectReason::UserRejected)
            .to_string()
            .contains("user rejected"));
        assert!(PairingError::Spake2Error("test".into())
            .to_string()
            .contains("test"));
        assert!(PairingError::InvalidTransition {
            expected: "A".into(),
            actual: "B".into(),
        }
        .to_string()
        .contains("expected A"));
    }

    // --- Debug doesn't leak secrets ---

    #[test]
    fn debug_does_not_leak_shared_key() {
        let identity = LocalIdentity::generate();
        let (mut session, _) =
            PairingSession::new_standard_initiator(identity, DEFAULT_PAIRING_TIMEOUT);
        session.set_shared_key(vec![0xDE, 0xAD, 0xBE, 0xEF]);
        let debug = format!("{session:?}");
        assert!(!debug.contains("DEAD"));
        assert!(!debug.contains("shared_key"));
    }
}
