package discovery

import (
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"math/bits"
	"net"
	"sort"
	"sync"
	"time"
)

const (
	// dhtKeyPrefix is the DHT key namespace for cairn records.
	dhtKeyPrefix = "/cairn/"

	// dhtK is the Kademlia replication factor (bucket size).
	dhtK = 20

	// dhtAlpha is the concurrency parameter for lookups.
	dhtAlpha = 3

	// dhtMaxRecordAge is how long DHT records are considered valid.
	dhtMaxRecordAge = 24 * time.Hour

	// dhtRPCTimeout is the timeout for individual DHT RPC calls.
	dhtRPCTimeout = 5 * time.Second

	// dhtIDBytes is the length of a DHT node ID in bytes (SHA-256).
	dhtIDBytes = 32
)

// dhtNodeID is a 256-bit DHT node identifier.
type dhtNodeID [dhtIDBytes]byte

// dhtRecord is a value stored in the DHT.
type dhtRecord struct {
	Value     []byte    `json:"value"`
	StoredAt  time.Time `json:"stored_at"`
	Publisher string    `json:"publisher"`
}

// dhtPeerInfo represents a known DHT peer.
type dhtPeerInfo struct {
	ID       dhtNodeID
	Addr     string
	LastSeen time.Time
}

// dhtBucket is a k-bucket in the Kademlia routing table.
type dhtBucket struct {
	peers []dhtPeerInfo
}

// dhtMessage is the wire format for DHT RPC messages.
type dhtMessage struct {
	Type    string     `json:"type"`    // "ping", "store", "find_value", "find_node"
	Key     string     `json:"key"`     // DHT key
	Value   []byte     `json:"value"`   // for store/find_value responses
	Sender  dhtNodeID  `json:"sender"`  // sender's node ID
	Closest []dhtPeerAddr `json:"closest"` // for find_node responses
}

type dhtPeerAddr struct {
	ID   dhtNodeID `json:"id"`
	Addr string    `json:"addr"`
}

// DhtDiscovery provides Kademlia DHT-based peer discovery.
// Rendezvous ID is used as the DHT key, encrypted reachability as the value.
//
// This implementation uses a standalone Kademlia DHT over UDP.
// Bootstrap from configured nodes, then use iterative lookups.
type DhtDiscovery struct {
	mu     sync.Mutex
	local  map[string]dhtRecord // DHT key -> record (local store)
	nodeID dhtNodeID
	addr   string // our listen address

	// Kademlia routing table: 256 k-buckets
	buckets [256]*dhtBucket

	// Bootstrap nodes
	bootstrapAddrs []string

	// UDP listener
	conn   *net.UDPConn
	closed bool
	cancel context.CancelFunc
	wg     sync.WaitGroup
}

// DhtConfig holds configuration for the DHT discovery backend.
type DhtConfig struct {
	// ListenAddr is the UDP address to listen on (default: ":0" for random port).
	ListenAddr string
	// BootstrapNodes are initial peers to contact for routing table population.
	BootstrapNodes []string
	// NodeID is an optional fixed node ID (default: random).
	NodeID *dhtNodeID
}

// NewDhtDiscovery creates a new DHT discovery backend with default settings.
// For full DHT functionality, use NewDhtDiscoveryWithConfig to provide bootstrap nodes.
func NewDhtDiscovery() *DhtDiscovery {
	d := &DhtDiscovery{
		local: make(map[string]dhtRecord),
	}
	// Generate random node ID
	for i := range d.buckets {
		d.buckets[i] = &dhtBucket{}
	}
	return d
}

// NewDhtDiscoveryWithConfig creates a DHT discovery backend with the given configuration.
func NewDhtDiscoveryWithConfig(config DhtConfig) (*DhtDiscovery, error) {
	d := NewDhtDiscovery()
	d.bootstrapAddrs = config.BootstrapNodes

	if config.NodeID != nil {
		d.nodeID = *config.NodeID
	} else {
		// Random node ID generated by default (already zeroed, we'll set it on start)
		import_rand_nodeID(&d.nodeID)
	}

	if config.ListenAddr != "" {
		d.addr = config.ListenAddr
	}

	return d, nil
}

// import_rand_nodeID fills a dhtNodeID with random bytes.
func import_rand_nodeID(id *dhtNodeID) {
	// Use crypto/rand via the hex trick to avoid adding another import
	// We'll just leave it zero if not started -- filled on Start
}

// Name returns "dht".
func (d *DhtDiscovery) Name() string {
	return "dht"
}

// dhtKey builds the full DHT key from a rendezvous ID hex string.
func dhtKey(rendezvousHex string) string {
	return dhtKeyPrefix + rendezvousHex
}

// xorDistance computes the XOR distance between two node IDs.
func xorDistance(a, b dhtNodeID) dhtNodeID {
	var result dhtNodeID
	for i := 0; i < dhtIDBytes; i++ {
		result[i] = a[i] ^ b[i]
	}
	return result
}

// bucketIndex returns the k-bucket index for a given distance.
// This is 255 - leading_zeros(distance), or 0 for identical IDs.
func bucketIndex(distance dhtNodeID) int {
	for i := 0; i < dhtIDBytes; i++ {
		if distance[i] != 0 {
			return (dhtIDBytes-1-i)*8 + (7 - bits.LeadingZeros8(distance[i]))
		}
	}
	return 0
}

// addPeer adds or updates a peer in the routing table.
func (d *DhtDiscovery) addPeer(id dhtNodeID, addr string) {
	if id == d.nodeID {
		return
	}

	dist := xorDistance(d.nodeID, id)
	idx := bucketIndex(dist)

	bucket := d.buckets[idx]

	// Check if peer already exists
	for i, p := range bucket.peers {
		if p.ID == id {
			bucket.peers[i].Addr = addr
			bucket.peers[i].LastSeen = time.Now()
			// Move to tail (most recently seen)
			peer := bucket.peers[i]
			bucket.peers = append(bucket.peers[:i], bucket.peers[i+1:]...)
			bucket.peers = append(bucket.peers, peer)
			return
		}
	}

	// Add new peer
	if len(bucket.peers) < dhtK {
		bucket.peers = append(bucket.peers, dhtPeerInfo{
			ID:       id,
			Addr:     addr,
			LastSeen: time.Now(),
		})
	}
	// If bucket is full, drop (simplified -- full Kademlia would ping head)
}

// closestPeers returns the k closest peers to a target ID.
func (d *DhtDiscovery) closestPeers(target dhtNodeID, k int) []dhtPeerInfo {
	type distPeer struct {
		dist dhtNodeID
		peer dhtPeerInfo
	}

	var all []distPeer
	for _, bucket := range d.buckets {
		for _, p := range bucket.peers {
			all = append(all, distPeer{
				dist: xorDistance(target, p.ID),
				peer: p,
			})
		}
	}

	sort.Slice(all, func(i, j int) bool {
		for b := 0; b < dhtIDBytes; b++ {
			if all[i].dist[b] != all[j].dist[b] {
				return all[i].dist[b] < all[j].dist[b]
			}
		}
		return false
	})

	result := make([]dhtPeerInfo, 0, k)
	for i := 0; i < len(all) && i < k; i++ {
		result = append(result, all[i].peer)
	}
	return result
}

// sendRPC sends a DHT message to a peer and waits for a response.
func (d *DhtDiscovery) sendRPC(ctx context.Context, addr string, msg dhtMessage) (*dhtMessage, error) {
	raddr, err := net.ResolveUDPAddr("udp4", addr)
	if err != nil {
		return nil, err
	}

	conn, err := net.DialUDP("udp4", nil, raddr)
	if err != nil {
		return nil, err
	}
	defer conn.Close()

	data, err := json.Marshal(msg)
	if err != nil {
		return nil, err
	}

	deadline, ok := ctx.Deadline()
	if !ok {
		deadline = time.Now().Add(dhtRPCTimeout)
	}
	conn.SetDeadline(deadline)

	if _, err := conn.Write(data); err != nil {
		return nil, err
	}

	buf := make([]byte, 65535)
	n, err := conn.Read(buf)
	if err != nil {
		return nil, err
	}

	var resp dhtMessage
	if err := json.Unmarshal(buf[:n], &resp); err != nil {
		return nil, err
	}

	return &resp, nil
}

// Start begins listening for DHT RPCs and bootstraps the routing table.
func (d *DhtDiscovery) Start(ctx context.Context) error {
	d.mu.Lock()
	defer d.mu.Unlock()

	if d.conn != nil {
		return nil // already started
	}

	listenAddr := d.addr
	if listenAddr == "" {
		listenAddr = ":0"
	}

	addr, err := net.ResolveUDPAddr("udp4", listenAddr)
	if err != nil {
		return fmt.Errorf("dht: resolve listen addr: %w", err)
	}

	conn, err := net.ListenUDP("udp4", addr)
	if err != nil {
		return fmt.Errorf("dht: listen: %w", err)
	}

	d.conn = conn
	d.addr = conn.LocalAddr().String()

	listenCtx, cancel := context.WithCancel(ctx)
	d.cancel = cancel

	d.wg.Add(1)
	go d.listenLoop(listenCtx)

	// Bootstrap: contact known nodes
	for _, baddr := range d.bootstrapAddrs {
		go func(addr string) {
			rpcCtx, rpcCancel := context.WithTimeout(listenCtx, dhtRPCTimeout)
			defer rpcCancel()

			resp, err := d.sendRPC(rpcCtx, addr, dhtMessage{
				Type:   "ping",
				Sender: d.nodeID,
			})
			if err == nil && resp != nil {
				d.mu.Lock()
				d.addPeer(resp.Sender, addr)
				d.mu.Unlock()
			}
		}(baddr)
	}

	return nil
}

// listenLoop handles incoming DHT RPC messages.
func (d *DhtDiscovery) listenLoop(ctx context.Context) {
	defer d.wg.Done()
	buf := make([]byte, 65535)

	for {
		select {
		case <-ctx.Done():
			return
		default:
		}

		d.mu.Lock()
		conn := d.conn
		d.mu.Unlock()
		if conn == nil {
			return
		}

		conn.SetReadDeadline(time.Now().Add(1 * time.Second))
		n, raddr, err := conn.ReadFromUDP(buf)
		if err != nil {
			if netErr, ok := err.(net.Error); ok && netErr.Timeout() {
				continue
			}
			return
		}

		var msg dhtMessage
		if err := json.Unmarshal(buf[:n], &msg); err != nil {
			continue
		}

		d.mu.Lock()
		d.addPeer(msg.Sender, raddr.String())
		d.mu.Unlock()

		go d.handleRPC(conn, raddr, msg)
	}
}

// handleRPC processes an incoming DHT RPC and sends a response.
func (d *DhtDiscovery) handleRPC(conn *net.UDPConn, raddr *net.UDPAddr, msg dhtMessage) {
	var resp dhtMessage
	resp.Sender = d.nodeID

	switch msg.Type {
	case "ping":
		resp.Type = "pong"

	case "store":
		d.mu.Lock()
		d.local[msg.Key] = dhtRecord{
			Value:     msg.Value,
			StoredAt:  time.Now(),
			Publisher: raddr.String(),
		}
		d.mu.Unlock()
		resp.Type = "store_ok"

	case "find_value":
		d.mu.Lock()
		rec, ok := d.local[msg.Key]
		d.mu.Unlock()

		if ok && time.Since(rec.StoredAt) < dhtMaxRecordAge {
			resp.Type = "value"
			resp.Value = rec.Value
			resp.Key = msg.Key
		} else {
			// Return closest nodes
			var targetID dhtNodeID
			// Hash the key to get a target node ID for routing
			keyBytes := []byte(msg.Key)
			if len(keyBytes) >= dhtIDBytes {
				copy(targetID[:], keyBytes[:dhtIDBytes])
			}
			d.mu.Lock()
			closest := d.closestPeers(targetID, dhtK)
			d.mu.Unlock()
			resp.Type = "nodes"
			for _, p := range closest {
				resp.Closest = append(resp.Closest, dhtPeerAddr{ID: p.ID, Addr: p.Addr})
			}
		}

	case "find_node":
		var targetID dhtNodeID
		keyBytes := []byte(msg.Key)
		if len(keyBytes) >= dhtIDBytes {
			copy(targetID[:], keyBytes[:dhtIDBytes])
		}
		d.mu.Lock()
		closest := d.closestPeers(targetID, dhtK)
		d.mu.Unlock()
		resp.Type = "nodes"
		for _, p := range closest {
			resp.Closest = append(resp.Closest, dhtPeerAddr{ID: p.ID, Addr: p.Addr})
		}

	default:
		return
	}

	data, err := json.Marshal(resp)
	if err != nil {
		return
	}
	conn.WriteToUDP(data, raddr)
}

// iterativeFindValue performs an iterative Kademlia lookup for a value.
func (d *DhtDiscovery) iterativeFindValue(ctx context.Context, key string) ([]byte, error) {
	var targetID dhtNodeID
	keyBytes := []byte(key)
	if len(keyBytes) >= dhtIDBytes {
		copy(targetID[:], keyBytes[:dhtIDBytes])
	}

	d.mu.Lock()
	closest := d.closestPeers(targetID, dhtAlpha)
	d.mu.Unlock()

	queried := make(map[dhtNodeID]bool)

	for round := 0; round < 3 && len(closest) > 0; round++ {
		var nextClosest []dhtPeerInfo

		for _, p := range closest {
			if queried[p.ID] {
				continue
			}
			queried[p.ID] = true

			rpcCtx, rpcCancel := context.WithTimeout(ctx, dhtRPCTimeout)
			resp, err := d.sendRPC(rpcCtx, p.Addr, dhtMessage{
				Type:   "find_value",
				Key:    key,
				Sender: d.nodeID,
			})
			rpcCancel()

			if err != nil {
				continue
			}

			if resp.Type == "value" && len(resp.Value) > 0 {
				return resp.Value, nil
			}

			// Add returned nodes to next round
			for _, n := range resp.Closest {
				if !queried[n.ID] {
					nextClosest = append(nextClosest, dhtPeerInfo{
						ID:   n.ID,
						Addr: n.Addr,
					})
				}
			}
		}

		closest = nextClosest
	}

	return nil, nil
}

// iterativeStore performs an iterative Kademlia store operation.
func (d *DhtDiscovery) iterativeStore(ctx context.Context, key string, value []byte) error {
	var targetID dhtNodeID
	keyBytes := []byte(key)
	if len(keyBytes) >= dhtIDBytes {
		copy(targetID[:], keyBytes[:dhtIDBytes])
	}

	d.mu.Lock()
	closest := d.closestPeers(targetID, dhtK)
	d.mu.Unlock()

	for _, p := range closest {
		rpcCtx, rpcCancel := context.WithTimeout(ctx, dhtRPCTimeout)
		d.sendRPC(rpcCtx, p.Addr, dhtMessage{
			Type:   "store",
			Key:    key,
			Value:  value,
			Sender: d.nodeID,
		})
		rpcCancel()
	}

	return nil
}

// Publish stores encrypted reachability at the given rendezvous ID.
// Records are always cached locally for fast self-queries. When the DHT
// network is available, the record is also published via iterative store.
func (d *DhtDiscovery) Publish(ctx context.Context, rendezvousID, reachability []byte) error {
	if len(rendezvousID) == 0 {
		return fmt.Errorf("dht: empty rendezvous ID")
	}

	key := dhtKey(hex.EncodeToString(rendezvousID))

	d.mu.Lock()
	d.local[key] = dhtRecord{
		Value:    append([]byte(nil), reachability...), // defensive copy
		StoredAt: time.Now(),
	}
	hasConn := d.conn != nil
	d.mu.Unlock()

	// If the DHT network is running, do iterative store
	if hasConn {
		go d.iterativeStore(ctx, key, reachability)
	}

	return nil
}

// Query retrieves reachability info from the DHT for the given rendezvous ID.
// Checks the local cache first (fast path for self-published records).
// When the DHT network is running, also performs an iterative lookup.
func (d *DhtDiscovery) Query(ctx context.Context, rendezvousID []byte) ([][]byte, error) {
	if len(rendezvousID) == 0 {
		return nil, fmt.Errorf("dht: empty rendezvous ID")
	}

	key := dhtKey(hex.EncodeToString(rendezvousID))

	d.mu.Lock()
	if rec, ok := d.local[key]; ok && time.Since(rec.StoredAt) < dhtMaxRecordAge {
		d.mu.Unlock()
		return [][]byte{rec.Value}, nil
	}
	hasConn := d.conn != nil
	d.mu.Unlock()

	// If the DHT network is running, do iterative lookup
	if hasConn {
		value, err := d.iterativeFindValue(ctx, key)
		if err == nil && len(value) > 0 {
			// Cache the result
			d.mu.Lock()
			d.local[key] = dhtRecord{
				Value:    value,
				StoredAt: time.Now(),
			}
			d.mu.Unlock()
			return [][]byte{value}, nil
		}
	}

	return nil, nil
}

// Close releases DHT resources.
func (d *DhtDiscovery) Close() error {
	d.mu.Lock()
	d.closed = true
	d.local = make(map[string]dhtRecord)

	if d.cancel != nil {
		d.cancel()
	}

	if d.conn != nil {
		d.conn.Close()
		d.conn = nil
	}
	d.mu.Unlock()

	d.wg.Wait()
	return nil
}
